### ISSUE TITLE
File uploader

### ISSUE THREAD

**Issue by petrsloup** [klokantech/javascript#1]
We need to create new javascript component that could be used to easily upload files to Amazon S3.

---

Inspiration at:
- http://filepicker.io/ or https://www.filepicker.com/pricing/
- https://uploadcare.com
- https://developers.kloudless.com/

Other components:
https://github.com/blueimp/jQuery-File-Upload

Amazon S3 JS for direct upload to their S3:
http://aws.amazon.com/sdk-for-browser/
http://aws.amazon.com/developers/getting-started/browser/
http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/browser-examples.html
for example:
https://www.mapbox.com/uploads/
https://www.mapbox.com/uploads/uploads.js

**Comment by klokan** [comment]
We have acquired Google Drive Unlimited storage for our company - to be used on backups of customers data. It would make sense to use Google Drive as the primary storage for this uploader.

A clean code for functioning chunked upload is available here:
https://github.com/googledrive/cors-upload-sample

It would need to be reworked (possibly with progress bar, drag&drop, verified support of more browsers), made more stable and turned to allow uploading to our company Google Drive account (token made with a server side OAuth2 for sysadmin@ account).

**Comment by klokan** [comment]
Tested. Runs great! Needs look&feel adjustments and serverside download script for the processing which will follow...

**Comment by klokan** [comment]
@petrsloup testing on IE & Firefox and mobile browsers probably required.

**Comment by petrsloup** [comment]
Can be tested at http://klokantech.github.io/javascript/upload.html (tokenprovider server needs to be running at http://localhost:8000 for this to work).
- "Choose file" button added.
- Minor UI improvements
- Successfully tested in latest Chrome, Firefox, IE10 & IE11
- In browsers without File API (IE9-, http://caniuse.com/#feat=fileapi) simple text  ("Your browser is not compatible with this file uploader. Please, upgrade your browser to the latest version.") is displayed.

Not tested in mobile browsers yet (this will be much easier once the token provider server runs somewhere online).

**Comment by klokan** [comment]
Cool!

Could you please automatically introduce the prefix/folder into which are the files uploaded, such as "/uploader/" - even for the tests it would be practical?

I guess we will not work on fallback for older browsers, right?
Something like a basic input and simple upload without progress only for a small file which would run in older browsers (=IE9) is very hard to do, right?

BTW Check our deprecated old project: http://uploaderapp.appspot.com/ (made in flash). Maybe we could revive this - I mean the person who worked on the project could implement small changes for backcompatibility).

**Comment by petrsloup** [comment]
The target folder needs to be specified by folder id, so it depends on the authorized account (the id is different for my local testing and for the sysadmin account) -- the easiest solution is to create the desired folder and pass the id as second parameter to the DriveUploader ctor.
E.g. `new kt.upload.DriveUploader(tokenProvider, '0B9wetF_QkGqMcGtZSjFDZ2IzdkU');`

Creating fallback for older browsers would not be very hard to do (simple `<input type="file" />` and `<form>` with POST), but it would require completely different server-side handling (I don't think it is possible to create valid Drive REST API request from a native `<form>`, so we would either have to "redirect" the file from our backend or even store the file on our servers).

**Comment by petrsloup** [comment]
To be implemented as a separate project: http://driveuploader.com/
