### ISSUE TITLE
MapQuest nominatim authentication

### ISSUE THREAD

**Issue by daliborjanak** [klokantech/javascript#3]
MapQuest changed api and needs auth key (also billing). http://open.mapquestapi.com/nominatim/

We need to find alternative solution for this and fix it in all projects:

- [x] MapSeries @petrsloup 
- [x] BoundingBox @petrsloup 
- [x] Georeferencer 3 @klokan
- [x] Georeferencer 4 @petrsloup
- [x] Cynefin @petrsloup
- [x] WebGLEarth 2 @petrsloup
- [x] NLSgaz @daliborjanak  
- [x] Omomobile @petrsloup + new deploy to stores
- [x] Maptiler Georeferencer - only replace url in build to relase 6.2 by @MartinMikita

**Comment by daliborjanak** [comment]
Note: Google changed billing for Maps API also geolocation:
https://developers.google.com/maps/pricing-and-plans/

**Comment by daliborjanak** [comment]
- [] BoundingBox @petrsloup 
- [] Georeferencer 3 @klokan
- [] NLSgaz @daliborjanak

**Comment by klokan** [comment]
New requests should be like:
http://nominatim.georeferencer.org/?q=Bern&format=json&json_callback=asdfas
(where nominatim.georeferencer.org is DNS CNAME to nominatim.mzk.cz - so http://nominatim.mzk.cz/?q=asdf&format=json

**Comment by MartinMikita** [comment]
MapTiler Georefencer fixed, building new binaries

**Comment by petrsloup** [comment]
- URL changed in boundingbox and gr4.
- MapSeries is fixed at http://klokan.github.io/mapseries/
  - [ ] @keosak Can you please update http://mapseries.klokantech.com/ethz/ ? -- copy build from `gh-pages`
- omo-mobile fixed and v1.0.4 created
  - Pushed as beta to the Play Store (update should soon be available to everybody in the beta testing community)
    - [ ] we can probably push this to production as soon as one of us verifies it works okay
  - [ ] @klokan Can you please update the iOS (ipa is at https://github.com/klokan/omo-mobile/releases/tag/v1.0.4) ?

**Comment by keosak** [comment]
@petrsloup Updated.

**Comment by petrsloup** [comment]
Cynefin (wordpress) and WebGLEarth 2 also updated

**Comment by daliborjanak** [comment]
@petrsloup OMOmobile tested. Works fine

**Comment by klokan** [comment]
App uploaded to iTunes Connect - it is going to be automatically released after it passes Apple review.

**Comment by klokan** [comment]
Gr3 is fixed. Closing. Thanks everybody!
