### ISSUE TITLE
Silktide Cookie Consent on DNN CMS

### ISSUE THREAD

**Issue by ttec72** [klokantech/javascript#4]
Hi,

I am having difficulty applying the Silktide generated code to my website. It is hosted on a private server, and I am unable to contact the owner.

The DNN CMS is not very easy to navigate. How do I go about making the site EU cookie compliant with the SlinObject.

I have managed to download the SkinObject to the server, but don't understand the next steps.

Any help would be appreciated.

Tony

**Comment by klokan** [comment]
Sorry, but this does not look like a issue of klokantech/javascript repository. Be more precise and we reopen.
