### ISSUE TITLE
Custom maps control WMS not working

### ISSUE THREAD

**Issue by klokan** [klokantech/javascript#8]
OpenLayers WMS does not run - for many services it returns "styles" argument missing.
The URL request must contain "styles=", not it contains only "styles".

See:
http://geoportal.gov.cz/ArcGIS/services/CENIA/cenia_rt_III_vojenske_mapovani/MapServer/WMSServer?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=0&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES=&BBOX=1605636.2161584124%2C6459540.3863236755%2C1605789.0902149829%2C6459693.260380246
vs
http://geoportal.gov.cz/ArcGIS/services/CENIA/cenia_rt_III_vojenske_mapovani/MapServer/WMSServer?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&FORMAT=image%2Fpng&TRANSPARENT=true&LAYERS=0&WIDTH=256&HEIGHT=256&CRS=EPSG%3A3857&STYLES&BBOX=1605636.2161584124%2C6459540.3863236755%2C1605789.0902149829%2C6459693.260380246

And try for example:
https://geoportal.gov.cz/web/guest/wms/
http://www.cuzk.cz/Katastr-nemovitosti/Poskytovani-udaju-z-KN/Webove-mapove-sluzby-pro-katastralni-mapy-(WMS-KN).aspx

This problem then bubble to all tools where we use OL3 and layer switcher.

**Comment by petrsloup** [comment]
This was a bug in OpenLayers v3.16.0 (v3.15.1 and v3.17.0 are ok): https://github.com/openlayers/openlayers/issues/5430

**Comment by klokan** [comment]
Experienced on Gr4 and GeoEditor - is this because affected OL is used?

**Comment by petrsloup** [comment]
I can add http://geoportal.gov.cz/ArcGIS/services/CENIA/cenia_rt_III_vojenske_mapovani/MapServer/WMSServer in geoeditor without any problems, does not work in gr4 (it uses ol 3.16.0).

http://services.cuzk.cz/wms/wms.asp works in both geoeditor and gr4 (this server is able to handle `&styles&...` correctly)

**Comment by klokan** [comment]
OK - gr4 update?

**Comment by petrsloup** [comment]
https://github.com/klokan/ol3private/issues/1
